In [ ]:

import numpy as np

In [ ]:
a = np.array([[7,5,3],[3,2,5],[1,2,1]])
np.linalg.det(a)

-34.00000000000001

In [ ]:
b = np.array([120,70,20])

In [ ]:
np.linalg.solve(a,b)

array([1.50000000e+01, 8.63506797e-16, 5.00000000e+00])

In [ ]:
np.linalg.matrix_rank(a)

3

In [ ]:
a = np.array([[0,1,1],[2,4,2],[1,2,1]])
np.linalg.matrix_rank(a)

2

In [ ]:
a = np.array([[7.5,5,12.5],[3,2,5],[0,0,0]])
np.linalg.matrix_rank(a)

1

In [ ]:
a = np.array([[7,5,3],[2,4,2],[1,2,1]])
np.linalg.matrix_rank(a)

In [ ]:
c = np.array([
             [1,2],
             [0,4]
             ])

In [ ]:
np.linalg.eig(c)

(array([1., 4.]),
 array([[1.        , 0.5547002 ],
        [0.        , 0.83205029]]))

In [ ]:
a = np.array([[-1,1],
              [-3,3]])
b = np.array([0,0])
np.linalg.inv(a) @ b

array([0., 0.])